"use client"

import Link from "next/link"
import { Scissors } from "lucide-react"

export interface AgentClipCard {
  video_row_id: string
  uid: string
  title: string
  hook: string
  confidence: number
}

/** "Clips from this video" — the Clip Agent's clips are platform videos; each card opens the watch page. */
export default function AgentClipsRow({ clips }: { clips: AgentClipCard[] }) {
  if (!clips || clips.length === 0) return null
  return (
    <div className="panel p-4 flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Scissors size={14} className="text-primary" />
        <h3 className="text-xs font-bold uppercase tracking-[0.15em] text-sa-text-3">Clips from this video</h3>
        <span className="text-xs text-muted-foreground">· auto-generated by the Clip Agent</span>
      </div>
      <div className="flex gap-3 overflow-x-auto pb-1 -mx-1 px-1">
        {clips.map((c) => (
          <Link key={c.video_row_id} href={`/watch/${c.video_row_id}`} className="group shrink-0 w-44">
            <div className="relative aspect-video rounded-xl overflow-hidden border border-border bg-black/40">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`https://videodelivery.net/${c.uid}/thumbnails/thumbnail.jpg?height=360`}
                alt={c.title}
                width={176}
                height={99}
                loading="lazy"
                decoding="async"
                className="w-full h-full object-cover transition-transform group-hover:scale-105"
              />
              {c.confidence > 0 && (
                <span className="absolute bottom-1.5 right-1.5 rounded bg-black/70 px-1.5 py-0.5 text-[10px] font-semibold">
                  {Math.round(c.confidence * 100)}%
                </span>
              )}
            </div>
            <p className="mt-1.5 text-xs font-medium leading-snug line-clamp-2 group-hover:text-primary transition-colors">{c.title}</p>
          </Link>
        ))}
      </div>
    </div>
  )
}
